# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 109bae62eb4c4546ebea7ccb8c3dd0cc0cc182f83587c64d00842b0700590e3769bf50c1b1215c6aaf26d18c9316f415b96c2a163b8cbf3fbfab58095a1e603c

test:
  secret_key_base: f891900ad161d5a1c107dfa5723e54e4c808ec88ecb5a1fdd05c98f0a37dd1c069fa5ba1b57347d08409fac5c413d7c5dae04b3ecb0c44fff2b8f4aff8888ac5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
